---
- name: Install NFS packages
  apt:
    name: nfs-kernel-server
    state: present
- name: Ceate the directories to be shared
  file:
   name: "{{ item }}" 
   state: directory
   mode: "u+rwx,g+rwx,o+rx"
  with_items: "{{ nfs_share_names }}"
- name: Configure the exports for NFS share
  template:
    src: exports.j2
    dest: /etc/exports
    backup: yes
  register: exportsfilestat
- name: Restart the NFS service  
  service:
    name: nfs-kernel-server
    state: restarted
  when: exportsfilestat.changed
