- include: install-yum-pkg.yml
  when: ansible_distribution == "Redhat" or ansible_distribution == "CentOS"
  tags: package-install

- include: install-apt-pkg.yml
  when: ansible_distribution == "Ubuntu"
  tags: package-install