#- include: install-yum-pkg.yml
#  when: ansible_distribution == "RedHat"
#  tags: package-install

- include: install-apt-pkg.yml
  when: ansible_distribution == "Ubuntu"
  tags: package-install