
- name: enable EPEL repo
  yum_repository:
    file: epel
    name: epel
    #baseurl: http://centos-hcm.viettelidc.com.vn
    baseurl: https://ftp.yz.yamagata-u.ac.jp/pub/linux/fedora-projects/epel/7/x86_64
    
    enabled: yes
    description: epel
    gpgcheck: no
  #tags: config-pkg
- name: Run yum update and upgrade
  yum:
    update_cache: yes
    name: '*'
    state: latest
    #upgrade: dist    
    disable_gpg_check: "{{ yum_gpg_check }}"
    validate_certs: "{{ yum_validate_certs }}"
  #tags:  config-pkg
  
- name: apply delta  using the command  yum provides '*/applydeltarpm'
  shell: " yum provides '*/applydeltarpm'"
  
