- name: Create apt.conf file where proxy for apt need to be mentioned
  file: path=/etc/apt/apt.conf  state=touch mode="u+rw,g-wx,o-wx"
  when: set_intenal_apt_mirror == False

- name: Insert apt proxy configuration in /etc/apt/apt.conf 
  blockinfile:
      dest: /etc/apt/apt.conf
      block: "{{ apt_proxy_entry }}"
  when: set_intenal_apt_mirror == False
  
- name: pointing to internal mirror  in /etc/apt/sources.list 
  template:
      source: sources.j2
      dest: /etc/apt/sources.list
      backup: yes
  when: set_intenal_apt_mirror == True
    
- name: Run the equivalent of "apt-get update"  and apt dist-upgrade as a separate step
  apt:
    update_cache: yes
    upgrade: dist