---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml    
  become: true
  
  roles:
   - role: configure-proxy-apt
     when: "'haproxy' not in target_hosts[ansible_hostname]['roles']"
   - role: configure-chrony #tag chrony
     when: "'ntpmaster' not in target_hosts[ansible_hostname]['roles']"
   - role: install-apt-pkg   
   - role: configure-nfs-server
     when: "'nfs'  in target_hosts[ansible_hostname]['roles']"
   - role: configure-iommu-for-nova-compute
     when: "'novacompute'  in target_hosts[ansible_hostname]['roles']"
   - role: create-interfaces-bridges #tag configure-network  
   
- hosts: localhost
  vars_files: 
    - base-hardware-prep-defination.yml    
  #become: true
  roles:   
   - role: reboot-servers #tag rebootserver
     
  