---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml    
  become: true
  
  roles:
   - role: configure-proxy-apt
     when: "ansible_hostname not in  haproxy_server_hostnames" 
   - role: configure-chrony #tag chrony
     when: "ntpmaster not in  target_hosts[ansible_hostname]['roles']"
   - role: install-apt-pkg   
   - role: configure-nfs-server
     when: "ansible_hostname  in nfs_server_hostnames"
   - role: configure-iommu-for-nova-compute
     when: "ansible_hostname in  nova_compute_server_hostnames"
   - role: create-interfaces-bridges #tag configure-network     
   - role: reboot-servers #tag rebootserver
     
  