---
- name: Basic lxc host setup
  hosts: "{{ lxc_host_group | default('lxc_hosts')}}"
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 20
  user: root
  pre_tasks:
#    - include: common-tasks/set-upper-constraints.yml
#    - include: common-tasks/set-pip-upstream-url.yml
    - name: Check the state of the default LXC service log directory
      stat:
        path: "/var/log/lxc"
      register: _lxc_log_dir
    - name: Create the log aggregation parent directory
      file:
        path: "/openstack/log"
        state: directory
    - name: Move the existing folder to the log aggregation parent
      command: "mv /var/log/lxc /openstack/log/{{ inventory_hostname }}-lxc"
      when:
        - _lxc_log_dir.stat.isdir is defined
        - _lxc_log_dir.stat.isdir | bool
    - name: Create the new LXC service log directory
      file:
        path: "/openstack/log/{{ inventory_hostname }}-lxc"
        state: directory
    - name: Create the LXC service log aggregation link
      file:
        src: "/openstack/log/{{ inventory_hostname }}-lxc"
        dest: "/var/log/lxc"
        state: "link"
  roles:
    - role: "lxc_hosts"
#    - role: "rsyslog_client"
#      rsyslog_client_log_rotate_file: lxc_log_rotate
#      rsyslog_client_log_dir: "/var/log/lxc"
#      rsyslog_client_config_name: "99-lxc-rsyslog-client.conf"
#      tags:
#        - rsyslog
#  vars_files:
#    - defaults/repo_packages/openstack_services.yml
  vars:
    pip_lock_to_internal_repo: False
  tags:
    - lxc-hosts
