---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml    
  become: true
     
  tasks: 
  - debug: 
     msg: "{{ target_hosts['infra2']['nic' ]}}"
  - name: Configure the network interfaces and bridges
    template:      
       src: base-hw-network.cfg.j2
       dest: /tmp/myfile
       backup: yes

