---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml    
  become: true
     
  tasks: 
  - debug:
      msg: "{{ ansible_ssh_host }}"
  - name: waiting for server to come back after reboot
    local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=3000 
    retries: 50

