---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml    
  become: true
     
  tasks: 
  
  - name: just do any job
    shell: ls
    vars:
      sname: {{ ansible_host }}
  - debug:
      msg:{{ sname }}

