---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml
  vars:
      sname: "{{ ansible_host }}"
      
  become: true
     
  tasks: 
  
  - name: just do any job
    shell: hostname
    register: result
    
  - debug:
      msg: result.stdout
      
- hosts: localhost
  tasks:
  - debug:
      msg: result.stdout
  - shell: "ssh@result.stdout"

