---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml
  vars:
      sname: "{{ ansible_host }}"
      
  become: true
     
  tasks: 
  
  - name: just do any job
    shell: hostname
    register: result
    
  - debug:
      msg: "{{ inventory_hostname }}"
  - name: Add new  Instance  name to ansible  Inventory  
    add_host:
      name: just_restarted
      #hostname: "{{ new_ip }}"
      ansible_host: "{{ inventory_hostname }}"    
      #ansible_port: "{{ new_port }}"
      #groups: just_restarted
            
      
- hosts: localhost
  tasks:
  - debug:
      msg: "{{ hostvars[just_restarted] }}"
  #- shell: "ssh@result.stdout"

