---
- hosts: base_hw_prep_for_openstack
  vars_files: 
    - base-hardware-prep-defination.yml
  vars:
      sname: "{{ ansible_host }}"
      
  become: true
     
  tasks: 
  
  - name: just do any job
    shell: ls
    register: result
    
  - debug:
      msg: result
      
- hosts: localhost
  tasks:
  - debug:
      msg: "{{ sname }}"
  - shell: "ssh@{{ sname }}"

